language: node_js

sudo: false

node_js:
  - "stable"

install:
  - npm i

script:
  - npm run lint
  - npm run coverage

after_script:
  - npm i -g codecov
  - nyc report --reporter=text-lcov > coverage.lcov
  - codecov
