language: node_js

sudo: false

node_js:
  - "6"

script:
  - npm run lint
  - npm run coverage
  - npm run build

after_script:
  - npm i -g codecov
  - nyc report --reporter=text-lcov > coverage.lcov
  - codecov
